---
- hosts: '{{ target }}'
  tasks:
  - name: copy tcp_check.conf
    copy:
      src: conf.yaml
      dest: /etc/datadog-agent/conf.d/tcp_check.d/conf.yaml

  - name: restart datadog-agent
    service:
      name: datadog-agent
      state: restarted
